version: "3"

services: 
  webapi:
    build:
      context: .
      dockerfile: ./dockerfile
    environment: 
      DOCKER-MONGO-HOST: 172.17.0.3
      DOCKER-MONGO-PORT: 27017
      DOCKER-AUTHCODE: authcode
    network_mode: bridge
    volumes:
      - ./logs:/logs
    ports: 
      - 32768:8080

