version: "3"

services: 
  web:
    build:
      context: .
      dockerfile: ./dockerfile
    environment: 
      DOCKER-MONGO-HOST: 172.20.0.3
      DOCKER-MONGO-PORT: 27017
      DOCKER-AUTHCODE: authcode
    ports: 
      - 32768:8080

