version: "3"

services: 
  mongo:
    image: mongo:bionic
    networks: 
      autocovid-v2:
        ipv4_address: 172.16.238.1
    ports: 
      - 37017:27017
  
  sanicapp:
    build:
      context: .
      dockerfile: ./dockerfile
    environment: 
      DOCKER-MONGO-HOST: 172.16.238.1
      DOCKER-MONGO-PORT: 27017
      DOCKER-AUTHCODE: authcode
    networks: 
      autocovid-v2:
        ipv4_address: 172.16.238.2
    ports: 
      - 32768:8080

networks:
  autocovid-v2:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"